- name: Azure 上的 Kubernetes
  href: ./index.yml
- name: 概述
- name: 快速入门
  expanded: true
- name: 教程
- name: 概念
- name: 操作指南
  items:
    - name: 使用 Azure 文件持久保存数据
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: 监视
    - name: 部署 Spring Boot 应用
      items:
        - name: 在 Azure 容器服务中将 Spring Boot 应用程序部署于 Linux 上
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: 在 Azure 容器服务中将 Spring Boot 应用程序部署于 Kubernetes 群集上
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: 使用 fabric8 Maven 插件部署 Spring Boot 应用
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: 参考
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: 资源
  items:
    - name: Azure 路线图
      href: 'https://azure.microsoft.com/roadmap/'
    - name: 模板 - ACS 引擎
      href: 'https://github.com/Azure/acs-engine'
    - name: 定价
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: 上市区域
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: 视频
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'