### YamlMime:Landing
title: Azure Arc Kubernetes（预览版）
summary: 了解如何使用 Azure Arc 管理 Kubernetes 群集
metadata:
  title: Azure Arc Kubernetes
  description: 了解如何管理 Azure 中的本地计算机
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: bc12e75904f375e2e40bce01d102186ec0d39f13
  ms.sourcegitcommit: 2c586a0fbec6968205f3dc2af20e89e01f1b74b5
  ms.translationtype: HT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 10/14/2020
  ms.locfileid: "92014250"
landingContent:
- title: 使用 Azure Arc 将 Kubernetes 群集连接到 Azure
  linkLists:
  - linkListType: overview
    links:
    - text: 什么是已启用 Azure Arc 的 Kubernetes？
      url: overview.md
  - linkListType: quickstart
    links:
    - text: 连接群集
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: 使用 GitOps 部署配置
      url: use-gitops-connected-cluster.md
    - text: 使用 GitOps 部署 Helm 图表
      url: use-gitops-with-helm.md
    - text: 通过 Azure Policy 强制使用 GitOps
      url: use-azure-policy.md
    - text: 部署 Azure IoT Edge 工作负载
      url: deploy-azure-iot-edge-workloads.md
- title: 参考体系结构
  linkLists:
  - linkListType: architecture
    links:
    - text: 管理混合 Kubernetes 群集的部署和配置
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
